---
- name: Install Ceph software
  become_user: ceph-deploy
  shell: ceph-deploy install --release kraken --no-adjust-repo ceph-osd1 ceph-osd2 ceph-osd3 docker

- name: Register initial monitors
  become_user: ceph-deploy
  shell: ceph-deploy new ceph-osd1 ceph-osd2 ceph-osd3

- ini_file: dest=/home/ceph-deploy/ceph.conf section=global option="osd pool default size" value=2
#- ini_file: dest=/home/ceph-deploy/ceph.ini section=global option="enable experimental unrecoverable data corrupting features" value="bluestore rocksdb"
#- ini_file: dest=/home/ceph-deploy/ceph.ini section=global option="osd objectstore" value=bluestore
#- ini_file: dest=/home/ceph-deploy/ceph.ini section=global option="bluestore fsck on mount" value=true
#- ini_file: dest=/home/ceph-deploy/ceph.ini section=global option="bluestore block db size" value=67108864
#- ini_file: dest=/home/ceph-deploy/ceph.ini section=global option="bluestore block wal size" value=134217728
#- ini_file: dest=/home/ceph-deploy/ceph.ini section=global option="bluestore block size" value=5368709120

- name: Create initial monitors
  become_user: ceph-deploy
  shell: ceph-deploy mon create-initial

- name: Prepare OSD directories
  become_user: ceph-deploy
  shell: ceph-deploy osd prepare ceph-osd1:/dev/sdb ceph-osd2:/dev/sdb ceph-osd3:/dev/sdb

- name: Activate OSDs
  become_user: ceph-deploy
  shell: ceph-deploy osd activate ceph-osd1:/dev/sdb1 ceph-osd2:/dev/sdb1 ceph-osd3:/dev/sdb1

- name: Distribute keys
  become_user: ceph-deploy
  shell: ceph-deploy admin ceph-osd1 ceph-osd2 ceph-osd3 docker
