---
- name: Create ceph-deploy group
  group: name=ceph-deploy gid=1163

- name: Create ceph-deploy user
  user: name=ceph-deploy group=ceph-deploy uid=1163

- name: Create .ssh directory for ceph-deploy
  file: path=/home/ceph-deploy/.ssh state=directory mode=700 owner=ceph-deploy group=ceph-deploy

- name: Configure sudo
  copy: src=roles/deploy/files/sudo dest=/etc/sudoers.d/ceph-deploy mode=0440 owner=root group=root

- name: Create ssh client config
  copy: src=roles/deploy/files/ssh_config dest=/home/ceph-deploy/.ssh/config owner=ceph-deploy group=ceph-deploy mode=0644

- name: Set ssh private key
  copy: src=roles/deploy/files/id_ecdsa dest=/home/ceph-deploy/.ssh/id_ecdsa owner=ceph-deploy group=ceph-deploy mode=0600
