---
- name: Create ceph-deploy group
  group: name=ceph-deploy gid=1163

- name: Create ceph-deploy user
  user: name=ceph-deploy group=ceph-deploy uid=1163

- name: Create .ssh directory for ceph-deploy
  file: path=/home/ceph-deploy/.ssh state=directory mode=700 owner=ceph-deploy group=ceph-deploy

- name: Configure sudo
  copy: src={{role_path}}/files/sudo dest=/etc/sudoers.d/ceph-deploy mode=0440 owner=root group=root

- name: Create ssh client config
  copy: src={{role_path}}/files/ssh_config dest=/home/ceph-deploy/.ssh/config owner=ceph-deploy group=ceph-deploy mode=0644

- name: Set ssh private key
  copy: src={{role_path}}/files/authorized_keys dest=/home/ceph-deploy/.ssh/authorized_keys owner=ceph-deploy group=ceph-deploy mode=0644

- name: Create ceph deploy group
  group: name=ceph gid=167

- name: Create ceph user
  user: name=ceph group=ceph uid=167

